name: Build

on:
  workflow_dispatch:

jobs:
  build:

    # runs-on: ubicloud-standard-16   ## nice, but the startup overhead is just too big
    runs-on: ubicloud-standard-4

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --release
