name: publish_crates

on:
  push:
    tags:
      - "*-beta"
      - "*-alpha"
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: ubicloud-standard-4

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

